### ISSUE TITLE
Cannot cycle import

### ISSUE THREAD

**Issue by yjhmelody** [LimeChain/as-scale-codec#64]
In code https://github.com/LimeChain/as-scale-codec/blob/master/assembly/interfaces/UnwrappableCodec.ts

These is a cycle import, so asc will be error if you try to build using `asc  UnwrappableCodec.ts`:
```
Error [AssertionError]: assertion failed
    at i.assert (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:735682)
    at new v (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:614789)
    at E.initialize (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:590313)
    at Object.t.initializeProgram (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\dist\assemblyscript.js:7:434145)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:798:20
    at measure (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:1242:3)
    at Object.main (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\cli\asc.js:797:27)
    at C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\bin\asc:19:47
C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\node_modules\binaryen\index.js:54
Ha.push({iu:function(){La()}});function Ma(){var b=a.preRun.shift();Ga.unshift(b)}var Na=0,Oa=null,Pa=null;a.preloadedImages={};a.preloadedAudios={};function q(b){if(a.onAbort)a.onAbort(b);v(b);wa=!0;throw new va("abort("+b+"). Build with -s ASSERTIONS=1 for more info.");}function Qa(b){var d=Ra;return String.prototype.startsWith?b.startsWith(d):0===b.indexOf(d)}var Ra="data:application/octet-stream;base64,",Sa="<<< WASM_BINARY_FILE >>>";

                 ^

Error: abort(AssertionError: assertion failed). Build with -s ASSERTIONS=1 for more info.
    at process.q (C:\Users\lenovo\AppData\Roaming\npm\node_modules\assemblyscript\node_modules\binaryen\index.js:54:207)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:200:22)
    at processPromiseRejections (node:internal/process/promises:221:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)

```

**Comment by yjhmelody** [comment]
It seems that there are some problems about my env, now I cannot reproduce it.
